#
# Module manifest for module 'GenXdev.Helpers'

@{

    # Script module or binary module file associated with this manifest.
    RootModule             = 'GenXdev.Helpers.psm1'

    # Version number of this module.
    ModuleVersion          = '1.36.2024'
    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID                   = '2f62080f-0483-4421-8497-b3d433b65173'

    # Author of this module
    Author                 = 'René Vaessen'

    # Company or vendor of this module
    CompanyName            = 'GenXdev'

    # Copyright statement for this module
    Copyright              = 'Copyright (c) 2021 René Vaessen'

    # Description of the functionality provided by this module
    Description            = 'A Windows PowerShell module with helpers mostly used by other GenXdev modules'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '5.1.19041.906'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.6.1'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    ClrVersion             = '4.0.0'

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules        = @(

    )

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = @(

        "GenXdev.Helpers.dll"
    )

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess       = @("GenXdev.Helpers.Load.ps1")

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no Cmdlets to export.
    CmdletsToExport        = '*'

    # Variables to export from this module
    VariablesToExport      = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    ModuleList             = @("GenXdev.Helpers")

    # List of all files packaged with this module
    FileList               = @(
            "Accessibility.dll",
            "aspnetcorev2_inprocess.dll",
            "BouncyCastle.Cryptography.dll",
            "clretwrc.dll",
            "clrgc.dll",
            "clrgcexp.dll",
            "clrjit.dll",
            "coreclr.dll",
            "createdump.exe",
            "D3DCompiler_47_cor3.dll",
            "DirectWriteForwarder.dll",
            "EmbedIO.dll",
            "GenXdev.Helpers.deps.json",
            "GenXdev.Helpers.dll",
            "GenXdev.Helpers.pdb",
            "GenXdev.Helpers.psd1",
            "GenXdev.Helpers.psm1",
            "getfilesiginforedist.dll",
            "getfilesiginforedistwrapper.dll",
            "hostfxr.dll",
            "hostpolicy.dll",
            "JetBrains.Annotations.dll",
            "Json.More.dll",
            "JsonPointer.Net.dll",
            "JsonSchema.Net.dll",
            "LICENSE",
            "license.txt",
            "Markdig.Signed.dll",
            "Microsoft.ApplicationInsights.dll",
            "Microsoft.AspNetCore.Antiforgery.dll",
            "Microsoft.AspNetCore.Authentication.Abstractions.dll",
            "Microsoft.AspNetCore.Authentication.BearerToken.dll",
            "Microsoft.AspNetCore.Authentication.Cookies.dll",
            "Microsoft.AspNetCore.Authentication.Core.dll",
            "Microsoft.AspNetCore.Authentication.dll",
            "Microsoft.AspNetCore.Authentication.OAuth.dll",
            "Microsoft.AspNetCore.Authorization.dll",
            "Microsoft.AspNetCore.Authorization.Policy.dll",
            "Microsoft.AspNetCore.Components.Authorization.dll",
            "Microsoft.AspNetCore.Components.dll",
            "Microsoft.AspNetCore.Components.Endpoints.dll",
            "Microsoft.AspNetCore.Components.Forms.dll",
            "Microsoft.AspNetCore.Components.Server.dll",
            "Microsoft.AspNetCore.Components.Web.dll",
            "Microsoft.AspNetCore.Connections.Abstractions.dll",
            "Microsoft.AspNetCore.CookiePolicy.dll",
            "Microsoft.AspNetCore.Cors.dll",
            "Microsoft.AspNetCore.Cryptography.Internal.dll",
            "Microsoft.AspNetCore.Cryptography.KeyDerivation.dll",
            "Microsoft.AspNetCore.DataProtection.Abstractions.dll",
            "Microsoft.AspNetCore.DataProtection.dll",
            "Microsoft.AspNetCore.DataProtection.Extensions.dll",
            "Microsoft.AspNetCore.Diagnostics.Abstractions.dll",
            "Microsoft.AspNetCore.Diagnostics.dll",
            "Microsoft.AspNetCore.Diagnostics.HealthChecks.dll",
            "Microsoft.AspNetCore.dll",
            "Microsoft.AspNetCore.HostFiltering.dll",
            "Microsoft.AspNetCore.Hosting.Abstractions.dll",
            "Microsoft.AspNetCore.Hosting.dll",
            "Microsoft.AspNetCore.Hosting.Server.Abstractions.dll",
            "Microsoft.AspNetCore.Html.Abstractions.dll",
            "Microsoft.AspNetCore.Http.Abstractions.dll",
            "Microsoft.AspNetCore.Http.Connections.Common.dll",
            "Microsoft.AspNetCore.Http.Connections.dll",
            "Microsoft.AspNetCore.Http.dll",
            "Microsoft.AspNetCore.Http.Extensions.dll",
            "Microsoft.AspNetCore.Http.Features.dll",
            "Microsoft.AspNetCore.Http.Results.dll",
            "Microsoft.AspNetCore.HttpLogging.dll",
            "Microsoft.AspNetCore.HttpOverrides.dll",
            "Microsoft.AspNetCore.HttpsPolicy.dll",
            "Microsoft.AspNetCore.Identity.dll",
            "Microsoft.AspNetCore.Localization.dll",
            "Microsoft.AspNetCore.Localization.Routing.dll",
            "Microsoft.AspNetCore.Metadata.dll",
            "Microsoft.AspNetCore.Mvc.Abstractions.dll",
            "Microsoft.AspNetCore.Mvc.ApiExplorer.dll",
            "Microsoft.AspNetCore.Mvc.Core.dll",
            "Microsoft.AspNetCore.Mvc.Cors.dll",
            "Microsoft.AspNetCore.Mvc.DataAnnotations.dll",
            "Microsoft.AspNetCore.Mvc.dll",
            "Microsoft.AspNetCore.Mvc.Formatters.Json.dll",
            "Microsoft.AspNetCore.Mvc.Formatters.Xml.dll",
            "Microsoft.AspNetCore.Mvc.Localization.dll",
            "Microsoft.AspNetCore.Mvc.Razor.dll",
            "Microsoft.AspNetCore.Mvc.RazorPages.dll",
            "Microsoft.AspNetCore.Mvc.TagHelpers.dll",
            "Microsoft.AspNetCore.Mvc.ViewFeatures.dll",
            "Microsoft.AspNetCore.OutputCaching.dll",
            "Microsoft.AspNetCore.RateLimiting.dll",
            "Microsoft.AspNetCore.Razor.dll",
            "Microsoft.AspNetCore.Razor.Runtime.dll",
            "Microsoft.AspNetCore.RequestDecompression.dll",
            "Microsoft.AspNetCore.ResponseCaching.Abstractions.dll",
            "Microsoft.AspNetCore.ResponseCaching.dll",
            "Microsoft.AspNetCore.ResponseCompression.dll",
            "Microsoft.AspNetCore.Rewrite.dll",
            "Microsoft.AspNetCore.Routing.Abstractions.dll",
            "Microsoft.AspNetCore.Routing.dll",
            "Microsoft.AspNetCore.Server.HttpSys.dll",
            "Microsoft.AspNetCore.Server.IIS.dll",
            "Microsoft.AspNetCore.Server.IISIntegration.dll",
            "Microsoft.AspNetCore.Server.Kestrel.Core.dll",
            "Microsoft.AspNetCore.Server.Kestrel.dll",
            "Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes.dll",
            "Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll",
            "Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll",
            "Microsoft.AspNetCore.Session.dll",
            "Microsoft.AspNetCore.SignalR.Common.dll",
            "Microsoft.AspNetCore.SignalR.Core.dll",
            "Microsoft.AspNetCore.SignalR.dll",
            "Microsoft.AspNetCore.SignalR.Protocols.Json.dll",
            "Microsoft.AspNetCore.StaticFiles.dll",
            "Microsoft.AspNetCore.WebSockets.dll",
            "Microsoft.AspNetCore.WebUtilities.dll",
            "Microsoft.Bcl.AsyncInterfaces.dll",
            "Microsoft.CodeAnalysis.CSharp.dll",
            "Microsoft.CodeAnalysis.dll",
            "Microsoft.CSharp.dll",
            "Microsoft.DiaSymReader.Native.amd64.dll",
            "Microsoft.Extensions.Caching.Abstractions.dll",
            "Microsoft.Extensions.Caching.Memory.dll",
            "Microsoft.Extensions.Configuration.Abstractions.dll",
            "Microsoft.Extensions.Configuration.Binder.dll",
            "Microsoft.Extensions.Configuration.CommandLine.dll",
            "Microsoft.Extensions.Configuration.dll",
            "Microsoft.Extensions.Configuration.EnvironmentVariables.dll",
            "Microsoft.Extensions.Configuration.FileExtensions.dll",
            "Microsoft.Extensions.Configuration.Ini.dll",
            "Microsoft.Extensions.Configuration.Json.dll",
            "Microsoft.Extensions.Configuration.KeyPerFile.dll",
            "Microsoft.Extensions.Configuration.UserSecrets.dll",
            "Microsoft.Extensions.Configuration.Xml.dll",
            "Microsoft.Extensions.DependencyInjection.Abstractions.dll",
            "Microsoft.Extensions.DependencyInjection.dll",
            "Microsoft.Extensions.Diagnostics.Abstractions.dll",
            "Microsoft.Extensions.Diagnostics.dll",
            "Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll",
            "Microsoft.Extensions.Diagnostics.HealthChecks.dll",
            "Microsoft.Extensions.Features.dll",
            "Microsoft.Extensions.FileProviders.Abstractions.dll",
            "Microsoft.Extensions.FileProviders.Composite.dll",
            "Microsoft.Extensions.FileProviders.Embedded.dll",
            "Microsoft.Extensions.FileProviders.Physical.dll",
            "Microsoft.Extensions.FileSystemGlobbing.dll",
            "Microsoft.Extensions.Hosting.Abstractions.dll",
            "Microsoft.Extensions.Hosting.dll",
            "Microsoft.Extensions.Http.dll",
            "Microsoft.Extensions.Identity.Core.dll",
            "Microsoft.Extensions.Identity.Stores.dll",
            "Microsoft.Extensions.Localization.Abstractions.dll",
            "Microsoft.Extensions.Localization.dll",
            "Microsoft.Extensions.Logging.Abstractions.dll",
            "Microsoft.Extensions.Logging.Configuration.dll",
            "Microsoft.Extensions.Logging.Console.dll",
            "Microsoft.Extensions.Logging.Debug.dll",
            "Microsoft.Extensions.Logging.dll",
            "Microsoft.Extensions.Logging.EventLog.dll",
            "Microsoft.Extensions.Logging.EventSource.dll",
            "Microsoft.Extensions.Logging.TraceSource.dll",
            "Microsoft.Extensions.ObjectPool.dll",
            "Microsoft.Extensions.Options.ConfigurationExtensions.dll",
            "Microsoft.Extensions.Options.DataAnnotations.dll",
            "Microsoft.Extensions.Options.dll",
            "Microsoft.Extensions.Primitives.dll",
            "Microsoft.Extensions.WebEncoders.dll",
            "Microsoft.JSInterop.dll",
            "Microsoft.Management.Infrastructure.CimCmdlets.dll",
            "microsoft.management.infrastructure.dll",
            "microsoft.management.infrastructure.native.dll",
            "microsoft.management.infrastructure.native.unmanaged.dll",
            "Microsoft.Net.Http.Headers.dll",
            "Microsoft.PowerShell.Commands.Diagnostics.dll",
            "Microsoft.PowerShell.Commands.Management.dll",
            "Microsoft.PowerShell.Commands.Utility.dll",
            "Microsoft.PowerShell.ConsoleHost.dll",
            "Microsoft.PowerShell.CoreCLR.Eventing.dll",
            "Microsoft.PowerShell.MarkdownRender.dll",
            "Microsoft.PowerShell.SDK.dll",
            "Microsoft.PowerShell.Security.dll",
            "Microsoft.VisualBasic.Core.dll",
            "Microsoft.VisualBasic.dll",
            "Microsoft.VisualBasic.Forms.dll",
            "Microsoft.Win32.Primitives.dll",
            "Microsoft.Win32.Registry.AccessControl.dll",
            "Microsoft.Win32.Registry.dll",
            "Microsoft.Win32.SystemEvents.dll",
            "Microsoft.Windows.SDK.NET.dll",
            "Microsoft.WSMan.Management.dll",
            "Microsoft.WSMan.Runtime.dll",
            "mscordaccore_amd64_amd64_9.0.24.17209.dll",
            "mscordaccore.dll",
            "mscordbi.dll",
            "mscorlib.dll",
            "mscorrc.dll",
            "msquic.dll",
            "netstandard.dll",
            "Newtonsoft.Json.dll",
            "OpenAI_API.dll",
            "PenImc_cor3.dll",
            "PowerShell.Core.Instrumentation.dll",
            "powershell.jpg",
            "PresentationCore.dll",
            "PresentationFramework-SystemCore.dll",
            "PresentationFramework-SystemData.dll",
            "PresentationFramework-SystemDrawing.dll",
            "PresentationFramework-SystemXml.dll",
            "PresentationFramework-SystemXmlLinq.dll",
            "PresentationFramework.Aero.dll",
            "PresentationFramework.Aero2.dll",
            "PresentationFramework.AeroLite.dll",
            "PresentationFramework.Classic.dll",
            "PresentationFramework.dll",
            "PresentationFramework.Luna.dll",
            "PresentationFramework.Royale.dll",
            "PresentationNative_cor3.dll",
            "PresentationUI.dll",
            "pwrshplugin.dll",
            "ReachFramework.dll",
            "README.md",
            "sni.dll",
            "SpotifyAPI.Web.Auth.dll",
            "SpotifyAPI.Web.dll",
            "SuperSocket.ClientEngine.dll",
            "Swan.Lite.dll",
            "System.AppContext.dll",
            "System.Buffers.dll",
            "System.CodeDom.dll",
            "System.Collections.Concurrent.dll",
            "System.Collections.dll",
            "System.Collections.Immutable.dll",
            "System.Collections.NonGeneric.dll",
            "System.Collections.Specialized.dll",
            "System.ComponentModel.Annotations.dll",
            "System.ComponentModel.Composition.dll",
            "System.ComponentModel.Composition.Registration.dll",
            "System.ComponentModel.DataAnnotations.dll",
            "System.ComponentModel.dll",
            "System.ComponentModel.EventBasedAsync.dll",
            "System.ComponentModel.Primitives.dll",
            "System.ComponentModel.TypeConverter.dll",
            "System.Configuration.ConfigurationManager.dll",
            "System.Configuration.dll",
            "System.Console.dll",
            "System.Core.dll",
            "System.Data.Common.dll",
            "System.Data.DataSetExtensions.dll",
            "System.Data.dll",
            "System.Data.Odbc.dll",
            "System.Data.OleDb.dll",
            "System.Data.SqlClient.dll",
            "System.Design.dll",
            "System.Diagnostics.Contracts.dll",
            "System.Diagnostics.Debug.dll",
            "System.Diagnostics.DiagnosticSource.dll",
            "System.Diagnostics.EventLog.dll",
            "System.Diagnostics.EventLog.Messages.dll",
            "System.Diagnostics.FileVersionInfo.dll",
            "System.Diagnostics.PerformanceCounter.dll",
            "System.Diagnostics.Process.dll",
            "System.Diagnostics.StackTrace.dll",
            "System.Diagnostics.TextWriterTraceListener.dll",
            "System.Diagnostics.Tools.dll",
            "System.Diagnostics.TraceSource.dll",
            "System.Diagnostics.Tracing.dll",
            "System.DirectoryServices.AccountManagement.dll",
            "System.DirectoryServices.dll",
            "System.DirectoryServices.Protocols.dll",
            "System.dll",
            "System.Drawing.Common.dll",
            "System.Drawing.Design.dll",
            "System.Drawing.dll",
            "System.Drawing.Primitives.dll",
            "System.Dynamic.Runtime.dll",
            "System.Formats.Asn1.dll",
            "System.Formats.Tar.dll",
            "System.Globalization.Calendars.dll",
            "System.Globalization.dll",
            "System.Globalization.Extensions.dll",
            "System.IO.Compression.Brotli.dll",
            "System.IO.Compression.dll",
            "System.IO.Compression.FileSystem.dll",
            "System.IO.Compression.Native.dll",
            "System.IO.Compression.ZipFile.dll",
            "System.IO.dll",
            "System.IO.FileSystem.AccessControl.dll",
            "System.IO.FileSystem.dll",
            "System.IO.FileSystem.DriveInfo.dll",
            "System.IO.FileSystem.Primitives.dll",
            "System.IO.FileSystem.Watcher.dll",
            "System.IO.IsolatedStorage.dll",
            "System.IO.MemoryMappedFiles.dll",
            "System.IO.Packaging.dll",
            "System.IO.Pipelines.dll",
            "System.IO.Pipes.AccessControl.dll",
            "System.IO.Pipes.dll",
            "System.IO.Ports.dll",
            "System.IO.UnmanagedMemoryStream.dll",
            "System.Linq.dll",
            "System.Linq.Expressions.dll",
            "System.Linq.Parallel.dll",
            "System.Linq.Queryable.dll",
            "System.Management.Automation.dll",
            "System.Management.dll",
            "System.Memory.dll",
            "System.Net.dll",
            "System.Net.Http.dll",
            "System.Net.Http.Json.dll",
            "System.Net.Http.WinHttpHandler.dll",
            "System.Net.HttpListener.dll",
            "System.Net.Mail.dll",
            "System.Net.NameResolution.dll",
            "System.Net.NetworkInformation.dll",
            "System.Net.Ping.dll",
            "System.Net.Primitives.dll",
            "System.Net.Quic.dll",
            "System.Net.Requests.dll",
            "System.Net.Security.dll",
            "System.Net.ServicePoint.dll",
            "System.Net.Sockets.dll",
            "System.Net.WebClient.dll",
            "System.Net.WebHeaderCollection.dll",
            "System.Net.WebProxy.dll",
            "System.Net.WebSockets.Client.dll",
            "System.Net.WebSockets.dll",
            "System.Numerics.dll",
            "System.Numerics.Vectors.dll",
            "System.ObjectModel.dll",
            "System.Printing.dll",
            "System.Private.CoreLib.dll",
            "System.Private.DataContractSerialization.dll",
            "System.Private.ServiceModel.dll",
            "System.Private.Uri.dll",
            "System.Private.Windows.Core.dll",
            "System.Private.Xml.dll",
            "System.Private.Xml.Linq.dll",
            "System.Reflection.Context.dll",
            "System.Reflection.DispatchProxy.dll",
            "System.Reflection.dll",
            "System.Reflection.Emit.dll",
            "System.Reflection.Emit.ILGeneration.dll",
            "System.Reflection.Emit.Lightweight.dll",
            "System.Reflection.Extensions.dll",
            "System.Reflection.Metadata.dll",
            "System.Reflection.Primitives.dll",
            "System.Reflection.TypeExtensions.dll",
            "System.Resources.Extensions.dll",
            "System.Resources.Reader.dll",
            "System.Resources.ResourceManager.dll",
            "System.Resources.Writer.dll",
            "System.Runtime.Caching.dll",
            "System.Runtime.CompilerServices.Unsafe.dll",
            "System.Runtime.CompilerServices.VisualC.dll",
            "System.Runtime.dll",
            "System.Runtime.Extensions.dll",
            "System.Runtime.Handles.dll",
            "System.Runtime.InteropServices.dll",
            "System.Runtime.InteropServices.JavaScript.dll",
            "System.Runtime.InteropServices.RuntimeInformation.dll",
            "System.Runtime.Intrinsics.dll",
            "System.Runtime.Loader.dll",
            "System.Runtime.Numerics.dll",
            "System.Runtime.Serialization.dll",
            "System.Runtime.Serialization.Formatters.dll",
            "System.Runtime.Serialization.Json.dll",
            "System.Runtime.Serialization.Primitives.dll",
            "System.Runtime.Serialization.Xml.dll",
            "System.Security.AccessControl.dll",
            "System.Security.Claims.dll",
            "System.Security.Cryptography.Algorithms.dll",
            "System.Security.Cryptography.Cng.dll",
            "System.Security.Cryptography.Csp.dll",
            "System.Security.Cryptography.dll",
            "System.Security.Cryptography.Encoding.dll",
            "System.Security.Cryptography.OpenSsl.dll",
            "System.Security.Cryptography.Pkcs.dll",
            "System.Security.Cryptography.Primitives.dll",
            "System.Security.Cryptography.ProtectedData.dll",
            "System.Security.Cryptography.X509Certificates.dll",
            "System.Security.Cryptography.Xml.dll",
            "System.Security.dll",
            "System.Security.Permissions.dll",
            "System.Security.Principal.dll",
            "System.Security.Principal.Windows.dll",
            "System.Security.SecureString.dll",
            "System.ServiceModel.dll",
            "System.ServiceModel.Duplex.dll",
            "System.ServiceModel.Http.dll",
            "System.ServiceModel.NetTcp.dll",
            "System.ServiceModel.Primitives.dll",
            "System.ServiceModel.Security.dll",
            "System.ServiceModel.Syndication.dll",
            "System.ServiceModel.Web.dll",
            "System.ServiceProcess.dll",
            "System.ServiceProcess.ServiceController.dll",
            "System.Speech.dll",
            "System.Text.Encoding.CodePages.dll",
            "System.Text.Encoding.dll",
            "System.Text.Encoding.Extensions.dll",
            "System.Text.Encodings.Web.dll",
            "System.Text.Json.dll",
            "System.Text.RegularExpressions.dll",
            "System.Threading.AccessControl.dll",
            "System.Threading.Channels.dll",
            "System.Threading.dll",
            "System.Threading.Overlapped.dll",
            "System.Threading.RateLimiting.dll",
            "System.Threading.Tasks.Dataflow.dll",
            "System.Threading.Tasks.dll",
            "System.Threading.Tasks.Extensions.dll",
            "System.Threading.Tasks.Parallel.dll",
            "System.Threading.Thread.dll",
            "System.Threading.ThreadPool.dll",
            "System.Threading.Timer.dll",
            "System.Transactions.dll",
            "System.Transactions.Local.dll",
            "System.ValueTuple.dll",
            "System.Web.dll",
            "System.Web.HttpUtility.dll",
            "System.Web.Services.Description.dll",
            "System.Windows.Controls.Ribbon.dll",
            "System.Windows.dll",
            "System.Windows.Extensions.dll",
            "System.Windows.Forms.Design.dll",
            "System.Windows.Forms.Design.Editors.dll",
            "System.Windows.Forms.dll",
            "System.Windows.Forms.Primitives.dll",
            "System.Windows.Input.Manipulations.dll",
            "System.Windows.Presentation.dll",
            "System.Xaml.dll",
            "System.Xml.dll",
            "System.Xml.Linq.dll",
            "System.Xml.ReaderWriter.dll",
            "System.Xml.Serialization.dll",
            "System.Xml.XDocument.dll",
            "System.Xml.XmlDocument.dll",
            "System.Xml.XmlSerializer.dll",
            "System.Xml.XPath.dll",
            "System.Xml.XPath.XDocument.dll",
            "UIAutomationClient.dll",
            "UIAutomationClientSideProviders.dll",
            "UIAutomationProvider.dll",
            "UIAutomationTypes.dll",
            "vcruntime140_cor3.dll",
            "WebSocket4Net.dll",
            "WindowsBase.dll",
            "WindowsFormsIntegration.dll",
            "WinRT.Runtime.dll",
            "wpfgfx_cor3.dll",
            "cs\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "cs\\Microsoft.CodeAnalysis.resources.dll",
            "cs\\Microsoft.VisualBasic.Forms.resources.dll",
            "cs\\PresentationCore.resources.dll",
            "cs\\PresentationFramework.resources.dll",
            "cs\\PresentationUI.resources.dll",
            "cs\\ReachFramework.resources.dll",
            "cs\\System.Private.ServiceModel.resources.dll",
            "cs\\System.Web.Services.Description.resources.dll",
            "cs\\System.Windows.Controls.Ribbon.resources.dll",
            "cs\\System.Windows.Forms.Design.resources.dll",
            "cs\\System.Windows.Forms.Primitives.resources.dll",
            "cs\\System.Windows.Forms.resources.dll",
            "cs\\System.Windows.Input.Manipulations.resources.dll",
            "cs\\System.Xaml.resources.dll",
            "cs\\UIAutomationClient.resources.dll",
            "cs\\UIAutomationClientSideProviders.resources.dll",
            "cs\\UIAutomationProvider.resources.dll",
            "cs\\UIAutomationTypes.resources.dll",
            "cs\\WindowsBase.resources.dll",
            "cs\\WindowsFormsIntegration.resources.dll",
            "de\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "de\\Microsoft.CodeAnalysis.resources.dll",
            "de\\Microsoft.VisualBasic.Forms.resources.dll",
            "de\\PresentationCore.resources.dll",
            "de\\PresentationFramework.resources.dll",
            "de\\PresentationUI.resources.dll",
            "de\\ReachFramework.resources.dll",
            "de\\System.Private.ServiceModel.resources.dll",
            "de\\System.Web.Services.Description.resources.dll",
            "de\\System.Windows.Controls.Ribbon.resources.dll",
            "de\\System.Windows.Forms.Design.resources.dll",
            "de\\System.Windows.Forms.Primitives.resources.dll",
            "de\\System.Windows.Forms.resources.dll",
            "de\\System.Windows.Input.Manipulations.resources.dll",
            "de\\System.Xaml.resources.dll",
            "de\\UIAutomationClient.resources.dll",
            "de\\UIAutomationClientSideProviders.resources.dll",
            "de\\UIAutomationProvider.resources.dll",
            "de\\UIAutomationTypes.resources.dll",
            "de\\WindowsBase.resources.dll",
            "de\\WindowsFormsIntegration.resources.dll",
            "es\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "es\\Microsoft.CodeAnalysis.resources.dll",
            "es\\Microsoft.VisualBasic.Forms.resources.dll",
            "es\\PresentationCore.resources.dll",
            "es\\PresentationFramework.resources.dll",
            "es\\PresentationUI.resources.dll",
            "es\\ReachFramework.resources.dll",
            "es\\System.Private.ServiceModel.resources.dll",
            "es\\System.Web.Services.Description.resources.dll",
            "es\\System.Windows.Controls.Ribbon.resources.dll",
            "es\\System.Windows.Forms.Design.resources.dll",
            "es\\System.Windows.Forms.Primitives.resources.dll",
            "es\\System.Windows.Forms.resources.dll",
            "es\\System.Windows.Input.Manipulations.resources.dll",
            "es\\System.Xaml.resources.dll",
            "es\\UIAutomationClient.resources.dll",
            "es\\UIAutomationClientSideProviders.resources.dll",
            "es\\UIAutomationProvider.resources.dll",
            "es\\UIAutomationTypes.resources.dll",
            "es\\WindowsBase.resources.dll",
            "es\\WindowsFormsIntegration.resources.dll",
            "fr\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "fr\\Microsoft.CodeAnalysis.resources.dll",
            "fr\\Microsoft.VisualBasic.Forms.resources.dll",
            "fr\\PresentationCore.resources.dll",
            "fr\\PresentationFramework.resources.dll",
            "fr\\PresentationUI.resources.dll",
            "fr\\ReachFramework.resources.dll",
            "fr\\System.Private.ServiceModel.resources.dll",
            "fr\\System.Web.Services.Description.resources.dll",
            "fr\\System.Windows.Controls.Ribbon.resources.dll",
            "fr\\System.Windows.Forms.Design.resources.dll",
            "fr\\System.Windows.Forms.Primitives.resources.dll",
            "fr\\System.Windows.Forms.resources.dll",
            "fr\\System.Windows.Input.Manipulations.resources.dll",
            "fr\\System.Xaml.resources.dll",
            "fr\\UIAutomationClient.resources.dll",
            "fr\\UIAutomationClientSideProviders.resources.dll",
            "fr\\UIAutomationProvider.resources.dll",
            "fr\\UIAutomationTypes.resources.dll",
            "fr\\WindowsBase.resources.dll",
            "fr\\WindowsFormsIntegration.resources.dll",
            "it\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "it\\Microsoft.CodeAnalysis.resources.dll",
            "it\\Microsoft.VisualBasic.Forms.resources.dll",
            "it\\PresentationCore.resources.dll",
            "it\\PresentationFramework.resources.dll",
            "it\\PresentationUI.resources.dll",
            "it\\ReachFramework.resources.dll",
            "it\\System.Private.ServiceModel.resources.dll",
            "it\\System.Web.Services.Description.resources.dll",
            "it\\System.Windows.Controls.Ribbon.resources.dll",
            "it\\System.Windows.Forms.Design.resources.dll",
            "it\\System.Windows.Forms.Primitives.resources.dll",
            "it\\System.Windows.Forms.resources.dll",
            "it\\System.Windows.Input.Manipulations.resources.dll",
            "it\\System.Xaml.resources.dll",
            "it\\UIAutomationClient.resources.dll",
            "it\\UIAutomationClientSideProviders.resources.dll",
            "it\\UIAutomationProvider.resources.dll",
            "it\\UIAutomationTypes.resources.dll",
            "it\\WindowsBase.resources.dll",
            "it\\WindowsFormsIntegration.resources.dll",
            "ja\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "ja\\Microsoft.CodeAnalysis.resources.dll",
            "ja\\Microsoft.VisualBasic.Forms.resources.dll",
            "ja\\PresentationCore.resources.dll",
            "ja\\PresentationFramework.resources.dll",
            "ja\\PresentationUI.resources.dll",
            "ja\\ReachFramework.resources.dll",
            "ja\\System.Private.ServiceModel.resources.dll",
            "ja\\System.Web.Services.Description.resources.dll",
            "ja\\System.Windows.Controls.Ribbon.resources.dll",
            "ja\\System.Windows.Forms.Design.resources.dll",
            "ja\\System.Windows.Forms.Primitives.resources.dll",
            "ja\\System.Windows.Forms.resources.dll",
            "ja\\System.Windows.Input.Manipulations.resources.dll",
            "ja\\System.Xaml.resources.dll",
            "ja\\UIAutomationClient.resources.dll",
            "ja\\UIAutomationClientSideProviders.resources.dll",
            "ja\\UIAutomationProvider.resources.dll",
            "ja\\UIAutomationTypes.resources.dll",
            "ja\\WindowsBase.resources.dll",
            "ja\\WindowsFormsIntegration.resources.dll",
            "ko\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "ko\\Microsoft.CodeAnalysis.resources.dll",
            "ko\\Microsoft.VisualBasic.Forms.resources.dll",
            "ko\\PresentationCore.resources.dll",
            "ko\\PresentationFramework.resources.dll",
            "ko\\PresentationUI.resources.dll",
            "ko\\ReachFramework.resources.dll",
            "ko\\System.Private.ServiceModel.resources.dll",
            "ko\\System.Web.Services.Description.resources.dll",
            "ko\\System.Windows.Controls.Ribbon.resources.dll",
            "ko\\System.Windows.Forms.Design.resources.dll",
            "ko\\System.Windows.Forms.Primitives.resources.dll",
            "ko\\System.Windows.Forms.resources.dll",
            "ko\\System.Windows.Input.Manipulations.resources.dll",
            "ko\\System.Xaml.resources.dll",
            "ko\\UIAutomationClient.resources.dll",
            "ko\\UIAutomationClientSideProviders.resources.dll",
            "ko\\UIAutomationProvider.resources.dll",
            "ko\\UIAutomationTypes.resources.dll",
            "ko\\WindowsBase.resources.dll",
            "ko\\WindowsFormsIntegration.resources.dll",
            "pl\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "pl\\Microsoft.CodeAnalysis.resources.dll",
            "pl\\Microsoft.VisualBasic.Forms.resources.dll",
            "pl\\PresentationCore.resources.dll",
            "pl\\PresentationFramework.resources.dll",
            "pl\\PresentationUI.resources.dll",
            "pl\\ReachFramework.resources.dll",
            "pl\\System.Private.ServiceModel.resources.dll",
            "pl\\System.Web.Services.Description.resources.dll",
            "pl\\System.Windows.Controls.Ribbon.resources.dll",
            "pl\\System.Windows.Forms.Design.resources.dll",
            "pl\\System.Windows.Forms.Primitives.resources.dll",
            "pl\\System.Windows.Forms.resources.dll",
            "pl\\System.Windows.Input.Manipulations.resources.dll",
            "pl\\System.Xaml.resources.dll",
            "pl\\UIAutomationClient.resources.dll",
            "pl\\UIAutomationClientSideProviders.resources.dll",
            "pl\\UIAutomationProvider.resources.dll",
            "pl\\UIAutomationTypes.resources.dll",
            "pl\\WindowsBase.resources.dll",
            "pl\\WindowsFormsIntegration.resources.dll",
            "pt-BR\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "pt-BR\\Microsoft.CodeAnalysis.resources.dll",
            "pt-BR\\Microsoft.VisualBasic.Forms.resources.dll",
            "pt-BR\\PresentationCore.resources.dll",
            "pt-BR\\PresentationFramework.resources.dll",
            "pt-BR\\PresentationUI.resources.dll",
            "pt-BR\\ReachFramework.resources.dll",
            "pt-BR\\System.Private.ServiceModel.resources.dll",
            "pt-BR\\System.Web.Services.Description.resources.dll",
            "pt-BR\\System.Windows.Controls.Ribbon.resources.dll",
            "pt-BR\\System.Windows.Forms.Design.resources.dll",
            "pt-BR\\System.Windows.Forms.Primitives.resources.dll",
            "pt-BR\\System.Windows.Forms.resources.dll",
            "pt-BR\\System.Windows.Input.Manipulations.resources.dll",
            "pt-BR\\System.Xaml.resources.dll",
            "pt-BR\\UIAutomationClient.resources.dll",
            "pt-BR\\UIAutomationClientSideProviders.resources.dll",
            "pt-BR\\UIAutomationProvider.resources.dll",
            "pt-BR\\UIAutomationTypes.resources.dll",
            "pt-BR\\WindowsBase.resources.dll",
            "pt-BR\\WindowsFormsIntegration.resources.dll",
            "ref\\Microsoft.CSharp.dll",
            "ref\\Microsoft.VisualBasic.Core.dll",
            "ref\\Microsoft.VisualBasic.dll",
            "ref\\Microsoft.Win32.Primitives.dll",
            "ref\\Microsoft.Win32.Registry.dll",
            "ref\\mscorlib.dll",
            "ref\\netstandard.dll",
            "ref\\System.AppContext.dll",
            "ref\\System.Buffers.dll",
            "ref\\System.Collections.Concurrent.dll",
            "ref\\System.Collections.dll",
            "ref\\System.Collections.Immutable.dll",
            "ref\\System.Collections.NonGeneric.dll",
            "ref\\System.Collections.Specialized.dll",
            "ref\\System.ComponentModel.Annotations.dll",
            "ref\\System.ComponentModel.DataAnnotations.dll",
            "ref\\System.ComponentModel.dll",
            "ref\\System.ComponentModel.EventBasedAsync.dll",
            "ref\\System.ComponentModel.Primitives.dll",
            "ref\\System.ComponentModel.TypeConverter.dll",
            "ref\\System.Configuration.dll",
            "ref\\System.Console.dll",
            "ref\\System.Core.dll",
            "ref\\System.Data.Common.dll",
            "ref\\System.Data.DataSetExtensions.dll",
            "ref\\System.Data.dll",
            "ref\\System.Diagnostics.Contracts.dll",
            "ref\\System.Diagnostics.Debug.dll",
            "ref\\System.Diagnostics.DiagnosticSource.dll",
            "ref\\System.Diagnostics.FileVersionInfo.dll",
            "ref\\System.Diagnostics.Process.dll",
            "ref\\System.Diagnostics.StackTrace.dll",
            "ref\\System.Diagnostics.TextWriterTraceListener.dll",
            "ref\\System.Diagnostics.Tools.dll",
            "ref\\System.Diagnostics.TraceSource.dll",
            "ref\\System.Diagnostics.Tracing.dll",
            "ref\\System.dll",
            "ref\\System.Drawing.dll",
            "ref\\System.Drawing.Primitives.dll",
            "ref\\System.Dynamic.Runtime.dll",
            "ref\\System.Formats.Asn1.dll",
            "ref\\System.Formats.Tar.dll",
            "ref\\System.Globalization.Calendars.dll",
            "ref\\System.Globalization.dll",
            "ref\\System.Globalization.Extensions.dll",
            "ref\\System.IO.Compression.Brotli.dll",
            "ref\\System.IO.Compression.dll",
            "ref\\System.IO.Compression.FileSystem.dll",
            "ref\\System.IO.Compression.ZipFile.dll",
            "ref\\System.IO.dll",
            "ref\\System.IO.FileSystem.AccessControl.dll",
            "ref\\System.IO.FileSystem.dll",
            "ref\\System.IO.FileSystem.DriveInfo.dll",
            "ref\\System.IO.FileSystem.Primitives.dll",
            "ref\\System.IO.FileSystem.Watcher.dll",
            "ref\\System.IO.IsolatedStorage.dll",
            "ref\\System.IO.MemoryMappedFiles.dll",
            "ref\\System.IO.Pipes.AccessControl.dll",
            "ref\\System.IO.Pipes.dll",
            "ref\\System.IO.UnmanagedMemoryStream.dll",
            "ref\\System.Linq.dll",
            "ref\\System.Linq.Expressions.dll",
            "ref\\System.Linq.Parallel.dll",
            "ref\\System.Linq.Queryable.dll",
            "ref\\System.Memory.dll",
            "ref\\System.Net.dll",
            "ref\\System.Net.Http.dll",
            "ref\\System.Net.Http.Json.dll",
            "ref\\System.Net.HttpListener.dll",
            "ref\\System.Net.Mail.dll",
            "ref\\System.Net.NameResolution.dll",
            "ref\\System.Net.NetworkInformation.dll",
            "ref\\System.Net.Ping.dll",
            "ref\\System.Net.Primitives.dll",
            "ref\\System.Net.Quic.dll",
            "ref\\System.Net.Requests.dll",
            "ref\\System.Net.Security.dll",
            "ref\\System.Net.ServicePoint.dll",
            "ref\\System.Net.Sockets.dll",
            "ref\\System.Net.WebClient.dll",
            "ref\\System.Net.WebHeaderCollection.dll",
            "ref\\System.Net.WebProxy.dll",
            "ref\\System.Net.WebSockets.Client.dll",
            "ref\\System.Net.WebSockets.dll",
            "ref\\System.Numerics.dll",
            "ref\\System.Numerics.Vectors.dll",
            "ref\\System.ObjectModel.dll",
            "ref\\System.Reflection.DispatchProxy.dll",
            "ref\\System.Reflection.dll",
            "ref\\System.Reflection.Emit.dll",
            "ref\\System.Reflection.Emit.ILGeneration.dll",
            "ref\\System.Reflection.Emit.Lightweight.dll",
            "ref\\System.Reflection.Extensions.dll",
            "ref\\System.Reflection.Metadata.dll",
            "ref\\System.Reflection.Primitives.dll",
            "ref\\System.Reflection.TypeExtensions.dll",
            "ref\\System.Resources.Reader.dll",
            "ref\\System.Resources.ResourceManager.dll",
            "ref\\System.Resources.Writer.dll",
            "ref\\System.Runtime.CompilerServices.Unsafe.dll",
            "ref\\System.Runtime.CompilerServices.VisualC.dll",
            "ref\\System.Runtime.dll",
            "ref\\System.Runtime.Extensions.dll",
            "ref\\System.Runtime.Handles.dll",
            "ref\\System.Runtime.InteropServices.dll",
            "ref\\System.Runtime.InteropServices.JavaScript.dll",
            "ref\\System.Runtime.InteropServices.RuntimeInformation.dll",
            "ref\\System.Runtime.Intrinsics.dll",
            "ref\\System.Runtime.Loader.dll",
            "ref\\System.Runtime.Numerics.dll",
            "ref\\System.Runtime.Serialization.dll",
            "ref\\System.Runtime.Serialization.Formatters.dll",
            "ref\\System.Runtime.Serialization.Json.dll",
            "ref\\System.Runtime.Serialization.Primitives.dll",
            "ref\\System.Runtime.Serialization.Xml.dll",
            "ref\\System.Security.AccessControl.dll",
            "ref\\System.Security.Claims.dll",
            "ref\\System.Security.Cryptography.Algorithms.dll",
            "ref\\System.Security.Cryptography.Cng.dll",
            "ref\\System.Security.Cryptography.Csp.dll",
            "ref\\System.Security.Cryptography.dll",
            "ref\\System.Security.Cryptography.Encoding.dll",
            "ref\\System.Security.Cryptography.OpenSsl.dll",
            "ref\\System.Security.Cryptography.Primitives.dll",
            "ref\\System.Security.Cryptography.X509Certificates.dll",
            "ref\\System.Security.dll",
            "ref\\System.Security.Principal.dll",
            "ref\\System.Security.Principal.Windows.dll",
            "ref\\System.Security.SecureString.dll",
            "ref\\System.ServiceModel.Web.dll",
            "ref\\System.ServiceProcess.dll",
            "ref\\System.Text.Encoding.CodePages.dll",
            "ref\\System.Text.Encoding.dll",
            "ref\\System.Text.Encoding.Extensions.dll",
            "ref\\System.Text.Encodings.Web.dll",
            "ref\\System.Text.Json.dll",
            "ref\\System.Text.RegularExpressions.dll",
            "ref\\System.Threading.Channels.dll",
            "ref\\System.Threading.dll",
            "ref\\System.Threading.Overlapped.dll",
            "ref\\System.Threading.Tasks.Dataflow.dll",
            "ref\\System.Threading.Tasks.dll",
            "ref\\System.Threading.Tasks.Extensions.dll",
            "ref\\System.Threading.Tasks.Parallel.dll",
            "ref\\System.Threading.Thread.dll",
            "ref\\System.Threading.ThreadPool.dll",
            "ref\\System.Threading.Timer.dll",
            "ref\\System.Transactions.dll",
            "ref\\System.Transactions.Local.dll",
            "ref\\System.ValueTuple.dll",
            "ref\\System.Web.dll",
            "ref\\System.Web.HttpUtility.dll",
            "ref\\System.Windows.dll",
            "ref\\System.Xml.dll",
            "ref\\System.Xml.Linq.dll",
            "ref\\System.Xml.ReaderWriter.dll",
            "ref\\System.Xml.Serialization.dll",
            "ref\\System.Xml.XDocument.dll",
            "ref\\System.Xml.XmlDocument.dll",
            "ref\\System.Xml.XmlSerializer.dll",
            "ref\\System.Xml.XPath.dll",
            "ref\\System.Xml.XPath.XDocument.dll",
            "ref\\WindowsBase.dll",
            "ru\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "ru\\Microsoft.CodeAnalysis.resources.dll",
            "ru\\Microsoft.VisualBasic.Forms.resources.dll",
            "ru\\PresentationCore.resources.dll",
            "ru\\PresentationFramework.resources.dll",
            "ru\\PresentationUI.resources.dll",
            "ru\\ReachFramework.resources.dll",
            "ru\\System.Private.ServiceModel.resources.dll",
            "ru\\System.Web.Services.Description.resources.dll",
            "ru\\System.Windows.Controls.Ribbon.resources.dll",
            "ru\\System.Windows.Forms.Design.resources.dll",
            "ru\\System.Windows.Forms.Primitives.resources.dll",
            "ru\\System.Windows.Forms.resources.dll",
            "ru\\System.Windows.Input.Manipulations.resources.dll",
            "ru\\System.Xaml.resources.dll",
            "ru\\UIAutomationClient.resources.dll",
            "ru\\UIAutomationClientSideProviders.resources.dll",
            "ru\\UIAutomationProvider.resources.dll",
            "ru\\UIAutomationTypes.resources.dll",
            "ru\\WindowsBase.resources.dll",
            "ru\\WindowsFormsIntegration.resources.dll",
            "runtimes\\win\\lib\\net8.0\\Modules\\CimCmdlets\\CimCmdlets.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Diagnostics\\Diagnostics.format.ps1xml",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Diagnostics\\Event.format.ps1xml",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Diagnostics\\GetEvent.types.ps1xml",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Diagnostics\\Microsoft.PowerShell.Diagnostics.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Host\\Microsoft.PowerShell.Host.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Management\\Microsoft.PowerShell.Management.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Security\\Microsoft.PowerShell.Security.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Security\\Security.types.ps1xml",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.PowerShell.Utility\\Microsoft.PowerShell.Utility.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.WSMan.Management\\Microsoft.WSMan.Management.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\Microsoft.WSMan.Management\\WSMan.format.ps1xml",
            "runtimes\\win\\lib\\net8.0\\Modules\\PSDiagnostics\\PSDiagnostics.psd1",
            "runtimes\\win\\lib\\net8.0\\Modules\\PSDiagnostics\\PSDiagnostics.psm1",
            "tr\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "tr\\Microsoft.CodeAnalysis.resources.dll",
            "tr\\Microsoft.VisualBasic.Forms.resources.dll",
            "tr\\PresentationCore.resources.dll",
            "tr\\PresentationFramework.resources.dll",
            "tr\\PresentationUI.resources.dll",
            "tr\\ReachFramework.resources.dll",
            "tr\\System.Private.ServiceModel.resources.dll",
            "tr\\System.Web.Services.Description.resources.dll",
            "tr\\System.Windows.Controls.Ribbon.resources.dll",
            "tr\\System.Windows.Forms.Design.resources.dll",
            "tr\\System.Windows.Forms.Primitives.resources.dll",
            "tr\\System.Windows.Forms.resources.dll",
            "tr\\System.Windows.Input.Manipulations.resources.dll",
            "tr\\System.Xaml.resources.dll",
            "tr\\UIAutomationClient.resources.dll",
            "tr\\UIAutomationClientSideProviders.resources.dll",
            "tr\\UIAutomationProvider.resources.dll",
            "tr\\UIAutomationTypes.resources.dll",
            "tr\\WindowsBase.resources.dll",
            "tr\\WindowsFormsIntegration.resources.dll",
            "zh-Hans\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "zh-Hans\\Microsoft.CodeAnalysis.resources.dll",
            "zh-Hans\\Microsoft.VisualBasic.Forms.resources.dll",
            "zh-Hans\\PresentationCore.resources.dll",
            "zh-Hans\\PresentationFramework.resources.dll",
            "zh-Hans\\PresentationUI.resources.dll",
            "zh-Hans\\ReachFramework.resources.dll",
            "zh-Hans\\System.Private.ServiceModel.resources.dll",
            "zh-Hans\\System.Web.Services.Description.resources.dll",
            "zh-Hans\\System.Windows.Controls.Ribbon.resources.dll",
            "zh-Hans\\System.Windows.Forms.Design.resources.dll",
            "zh-Hans\\System.Windows.Forms.Primitives.resources.dll",
            "zh-Hans\\System.Windows.Forms.resources.dll",
            "zh-Hans\\System.Windows.Input.Manipulations.resources.dll",
            "zh-Hans\\System.Xaml.resources.dll",
            "zh-Hans\\UIAutomationClient.resources.dll",
            "zh-Hans\\UIAutomationClientSideProviders.resources.dll",
            "zh-Hans\\UIAutomationProvider.resources.dll",
            "zh-Hans\\UIAutomationTypes.resources.dll",
            "zh-Hans\\WindowsBase.resources.dll",
            "zh-Hans\\WindowsFormsIntegration.resources.dll",
            "zh-Hant\\Microsoft.CodeAnalysis.CSharp.resources.dll",
            "zh-Hant\\Microsoft.CodeAnalysis.resources.dll",
            "zh-Hant\\Microsoft.VisualBasic.Forms.resources.dll",
            "zh-Hant\\PresentationCore.resources.dll",
            "zh-Hant\\PresentationFramework.resources.dll",
            "zh-Hant\\PresentationUI.resources.dll",
            "zh-Hant\\ReachFramework.resources.dll",
            "zh-Hant\\System.Private.ServiceModel.resources.dll",
            "zh-Hant\\System.Web.Services.Description.resources.dll",
            "zh-Hant\\System.Windows.Controls.Ribbon.resources.dll",
            "zh-Hant\\System.Windows.Forms.Design.resources.dll",
            "zh-Hant\\System.Windows.Forms.Primitives.resources.dll",
            "zh-Hant\\System.Windows.Forms.resources.dll",
            "zh-Hant\\System.Windows.Input.Manipulations.resources.dll",
            "zh-Hant\\System.Xaml.resources.dll",
            "zh-Hant\\UIAutomationClient.resources.dll",
            "zh-Hant\\UIAutomationClientSideProviders.resources.dll",
            "zh-Hant\\UIAutomationProvider.resources.dll",
            "zh-Hant\\UIAutomationTypes.resources.dll",
            "zh-Hant\\WindowsBase.resources.dll",
            "zh-Hant\\WindowsFormsIntegration.resources.dll"
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                     = 'GenXdev'

            # A URL to the license for this module.
            LicenseUri               = 'https://raw.githubusercontent.com/genXdev/GenXdev.Helpers/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri               = 'https://github.com/genXdev/GenXdev.Helpers'

            # A URL to an icon representing this module.
            IconUri                  = 'https://genxdev.net/favicon.ico'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $true

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI            = 'https://github.com/genXdev/GenXdev.Helpers/blob/main/README.md#cmdlet-index'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
